-- b3_contracts_2026_2027.sql
-- Generated by supabase/seed/seed_b3_calendar.py
-- Reference date (front-month determination): 2026-06-16
--
-- Month code reference:
--   F=Jan G=Feb H=Mar J=Apr K=May M=Jun
--   N=Jul Q=Aug U=Sep V=Oct X=Nov Z=Dec
--
-- WIN% / WDO%: even-month contracts (G J M Q V Z)
-- BIT%: monthly contracts (all 12 month codes)

-- Truncate + reload is safe; this is reference data only.
TRUNCATE TABLE b3_contracts RESTART IDENTITY;

insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITF26', '2026-01-16', false, '2026-01-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOG26', '2026-02-18', false, '2026-02-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WING26', '2026-02-18', false, '2026-02-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITG26', '2026-02-20', false, '2026-02-13');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITH26', '2026-03-20', false, '2026-03-13');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOJ26', '2026-04-15', false, '2026-04-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINJ26', '2026-04-15', false, '2026-04-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITJ26', '2026-04-17', false, '2026-04-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITK26', '2026-05-15', false, '2026-05-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOM26', '2026-06-17', true, '2026-06-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINM26', '2026-06-17', true, '2026-06-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITM26', '2026-06-19', true, '2026-06-12');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITN26', '2026-07-17', false, '2026-07-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOQ26', '2026-08-12', false, '2026-08-05');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINQ26', '2026-08-12', false, '2026-08-05');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITQ26', '2026-08-21', false, '2026-08-14');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITU26', '2026-09-18', false, '2026-09-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOV26', '2026-10-14', false, '2026-10-07');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINV26', '2026-10-14', false, '2026-10-07');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITV26', '2026-10-16', false, '2026-10-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITX26', '2026-11-20', false, '2026-11-13');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOZ26', '2026-12-16', false, '2026-12-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINZ26', '2026-12-16', false, '2026-12-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITZ26', '2026-12-18', false, '2026-12-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITF27', '2027-01-15', false, '2027-01-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOG27', '2027-02-17', false, '2027-02-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WING27', '2027-02-17', false, '2027-02-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITG27', '2027-02-19', false, '2027-02-12');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITH27', '2027-03-19', false, '2027-03-12');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOJ27', '2027-04-14', false, '2027-04-07');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINJ27', '2027-04-14', false, '2027-04-07');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITJ27', '2027-04-16', false, '2027-04-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITK27', '2027-05-21', false, '2027-05-14');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOM27', '2027-06-16', false, '2027-06-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINM27', '2027-06-16', false, '2027-06-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITM27', '2027-06-18', false, '2027-06-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITN27', '2027-07-16', false, '2027-07-09');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOQ27', '2027-08-18', false, '2027-08-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINQ27', '2027-08-18', false, '2027-08-11');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITQ27', '2027-08-20', false, '2027-08-13');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITU27', '2027-09-17', false, '2027-09-10');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOV27', '2027-10-13', false, '2027-10-06');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINV27', '2027-10-13', false, '2027-10-06');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITV27', '2027-10-15', false, '2027-10-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITX27', '2027-11-19', false, '2027-11-12');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WDO%', 'WDOZ27', '2027-12-15', false, '2027-12-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('WIN%', 'WINZ27', '2027-12-15', false, '2027-12-08');
insert into b3_contracts (asset, symbol, expiry_date, is_front_month, rollover_date) values ('BIT%', 'BITZ27', '2027-12-17', false, '2027-12-10');

-- Verification: exactly one front month per asset
-- SELECT asset, symbol, expiry_date FROM b3_contracts WHERE is_front_month = true ORDER BY asset;
